// Code generated by "stringer -type=Color -marshal -reverse color.go"; DO NOT EDIT.

package main

import (
	"fmt"
	"strconv"
	"strings"
	"unsafe"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Red-0]
	_ = x[Green-1]
	_ = x[Blue-2]
	_ = x[Yellow-3]
}

const _Color_name = "RedGreenBlueYellow"

var _Color_index = [...]uint8{0, 3, 8, 12, 18}

func (i Color) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Color_index)-1 {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[idx]:_Color_index[idx+1]]
}

var _Color_rindex = map[string]Color{
	"Red":    Red,
	"Green":  Green,
	"Blue":   Blue,
	"Yellow": Yellow,
}

var _Color_rindex_insensitive = map[string]Color{
	"red":    Red,
	"green":  Green,
	"blue":   Blue,
	"yellow": Yellow,
}

func ReverseColor(s string, caseSensitive bool) (Color, bool) {
	if caseSensitive {
		if val, ok := _Color_rindex[s]; ok {
			return val, true
		}
	} else {
		if val, ok := _Color_rindex_insensitive[strings.ToLower(s)]; ok {
			return val, true
		}
	}
	var zero Color
	return zero, false
}

func (i Color) MarshalJSON() ([]byte, error) {
	s := i.String()
	return []byte(`"` + s + `"`), nil
}

func (i *Color) UnmarshalJSON(data []byte) error {
	if len(data) < 2 || data[0] != '"' || data[len(data)-1] != '"' {
		return fmt.Errorf("invalid JSON string for Color")
	}
	var s string
	if len(data) > 2 {
		s = unsafe.String(&data[1], len(data)-2)
	}
	val, ok := ReverseColor(s, true)
	if !ok {
		return fmt.Errorf("invalid Color value: %s", s)
	}
	*i = val
	return nil
}
