// Code generated by "stringer -type=Level -valid -reverse -invalid=0 testdata/level.go"; DO NOT EDIT.

package main

import (
	"strconv"
	"strings"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Low-1]
	_ = x[Medium-2]
	_ = x[High-3]
	_ = x[Critical-4]
}

const _Level_name = "UndefinedLowMediumHighCritical"

var _Level_index = [...]uint8{0, 9, 12, 18, 22, 30}

func (i Level) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Level_index)-1 {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[idx]:_Level_index[idx+1]]
}

func (i Level) Valid() bool {
	if i == 0 {
		return false
	}
	idx := int(i) - 0
	if i < 0 || idx >= len(_Level_index)-1 {
		return false
	}
	return true
}

var _Level_rindex = map[string]Level{
	"Undefined": Undefined,
	"Low":       Low,
	"Medium":    Medium,
	"High":      High,
	"Critical":  Critical,
}

var _Level_rindex_insensitive = map[string]Level{
	"undefined": Undefined,
	"low":       Low,
	"medium":    Medium,
	"high":      High,
	"critical":  Critical,
}

func ReverseLevel(s string, caseSensitive bool) (Level, bool) {
	if caseSensitive {
		if val, ok := _Level_rindex[s]; ok {
			return val, val.Valid()
		}
	} else {
		if val, ok := _Level_rindex_insensitive[strings.ToLower(s)]; ok {
			return val, val.Valid()
		}
	}
	var zero Level
	return zero, false
}
