// Code generated by "stringer -type=Status -valid -reverse testdata/status.go"; DO NOT EDIT.

package main

import (
	"strconv"
	"strings"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Pending-0]
	_ = x[Active-1]
	_ = x[Completed-2]
	_ = x[Failed-3]
}

const _Status_name = "PendingActiveCompletedFailed"

var _Status_index = [...]uint8{0, 7, 13, 22, 28}

func (i Status) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[idx]:_Status_index[idx+1]]
}

func (i Status) Valid() bool {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Status_index)-1 {
		return false
	}
	return true
}

var _Status_rindex = map[string]Status{
	"Pending":   Pending,
	"Active":    Active,
	"Completed": Completed,
	"Failed":    Failed,
}

var _Status_rindex_insensitive = map[string]Status{
	"pending":   Pending,
	"active":    Active,
	"completed": Completed,
	"failed":    Failed,
}

func ReverseStatus(s string, caseSensitive bool) Status {
	if caseSensitive {
		if val, ok := _Status_rindex[s]; ok {
			return val
		}
	} else {
		if val, ok := _Status_rindex_insensitive[strings.ToLower(s)]; ok {
			return val
		}
	}
	return -1
}
